"""
init

Revision ID: feed623dcaaa
Revises: 
Create Date: 2021-10-13 22:31:07.726500
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'feed623dcaaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configkv',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configkv_id'), 'configkv', ['id'], unique=False)
    op.create_index(op.f('ix_configkv_key'), 'configkv', ['key'], unique=False)
    op.create_index(op.f('ix_configkv_value'), 'configkv', ['value'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_disabled'), 'user', ['disabled'], unique=False)
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.drop_index(op.f('ix_user_disabled'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_configkv_value'), table_name='configkv')
    op.drop_index(op.f('ix_configkv_key'), table_name='configkv')
    op.drop_index(op.f('ix_configkv_id'), table_name='configkv')
    op.drop_table('configkv')
    # ### end Alembic commands ###
