version: "3.8"
services:

  mppw:
    image: ascc/mppapi:${MPPW_VERSION:-dev}
    ports:
      - "8001:8000"
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}

  mongodb:
    image: mongo:4.4.6
    volumes:
      - data-db:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=admin

volumes:
  data-db:
