version: "3.8"
services:

  mppw:
    image: ascc/mppw:${MPPW_VERSION:-dev}
    ports:
      - "80:8000"
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGODB_URL: mongodb://mongodb:27017/mppw?authSource=admin
      MONGODB_ADMIN_USERNAME: ${MONGODB_ADMIN_USERNAME:-admin}
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD:-password}

  mongodb:
    image: ascc/mppw-mongodb:${MPPW_VERSION:-dev}
    volumes:
      - data-db:/data/db
    #ports:
    #  - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=admin
      - 'MONGO_INITRS_CONFIG={ "_id": "mppw0", "version": 1,  "members": [{ "_id": 0, "host": "mongodb:27017"}] }'
    command: ["mongod", "--replSet", "mppw0", "--keyFile", "/root_password_keyfile.key"]

volumes:
  data-db:
