version: "3.8"
services:

  mppw:
    image: ascc/mppw:${MPPW_VERSION:-dev}
    ports:
      - "${MPPW_EXTERNAL_PORT:-80}:8000"
    environment:
      MPPW_ADMIN_USERNAME: ${MPPW_ADMIN_USERNAME:-}
      MPPW_ADMIN_PASSWORD: ${MPPW_ADMIN_PASSWORD:-}
      WAIT_HOSTS: mongodb
      MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb/mppw?authSource=admin}
      MONGODB_ADMIN_USERNAME: ${MONGODB_ADMIN_USERNAME:-admin}
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}

  mongodb:
    image: ascc/mppw-mongodb:${MPPW_VERSION:-dev}
    volumes:
      - data:/data
    ports:
      - "${MONGODB_EXTERNAL_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD:?MONGODB_ADMIN_PASSWORD is required.}
      MONGO_INITDB_DATABASE: admin
      MONGO_INITRS_CONFIG: '{ "_id": "mppw0", "version": 1,  "members": [{ "_id": 0, "host": "mongodb:27017"}] }'
    command: ["mongod", "--replSet", "mppw0", "--keyFile", "/root_password_keyfile.key"]

volumes:
  data:
