version: "3.8"
services:

  mppw:
    image: ascc/mppw:${MPPW_VERSION:-dev}
    restart: unless-stopped
    environment:
      MPPW_ADMIN_USERNAME: ${MPPW_ADMIN_USERNAME:-}
      MPPW_ADMIN_PASSWORD: ${MPPW_ADMIN_PASSWORD:-}
      MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb/mppw?authSource=admin&tls=true&tlsAllowInvalidCertificates=true}
      MONGODB_ADMIN_USERNAME: ${MONGODB_ADMIN_USERNAME:-admin}
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}

  mongodb:
    image: ascc/mppw-mongodb:${MPPW_VERSION:-dev}
    restart: unless-stopped
    volumes:
      - certificates:/etc/certificates
      - data_db:/data/db
      - data_configdb:/data/configdb
    ports:
      - "${MONGODB_EXTERNAL_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD:?MONGODB_ADMIN_PASSWORD is required.}
      MONGO_INITDB_DATABASE: admin
      MONGO_INITRS_CONFIG: '{ "_id": "${MONGODB_INITRS_NAME:-mppw0}", "version": 1,  "members": [{ "_id": 0, "host": "mongodb:27017"}] }'
      MONGO_INITRS_TLS: 1
    command: ["mongod", "--tlsMode", "preferTLS", "--tlsCertificateKeyFile", "/etc/certificates/mongodb/key-cert.pem", "--replSet", "${MONGODB_INITRS_NAME:-mppw0}", "--keyFile", "/etc/certificates/mongodb/root-password-keyfile.key"]

  jupyterhub:
    image: ascc/mppw-jupyterhub:${MPPW_VERSION:-dev}
    restart: unless-stopped
    volumes:
      - data_notebooks:/home
    environment:
      ADMIN_USERNAME: ${JUPYTERHUB_ADMIN_USERNAME:-admin}
      AUTHENTICATOR_MPPW_URL: ${AUTHENTICATOR_MPPW_URL:-http://mppw:8000/api}

  nginx:
    image: ascc/mppw-nginx:${MPPW_VERSION:-dev}
    restart: unless-stopped
    volumes:
      - certificates:/etc/certificates
    ports:
      - 80:80
      - 443:443
    environment:
      PROXY_PASS: http://mppw:8000
      PROXY_PASS_JUPYTERHUB: http://jupyterhub:8000
      # Set to docker dns to allow for partial service spinup
      # https://stackoverflow.com/questions/42720618/docker-nginx-stopped-emerg-11-host-not-found-in-upstream
      PROXY_RESOLVER: "${PROXY_RESOLVER:-resolver 127.0.0.11 valid=30s; resolver_timeout 3s;}"
      MPPW_PROXY_ENABLED: ${MPPW_PROXY_ENABLED:-1}
      JUPYTERHUB_PROXY_ENABLED: ${JUPYTERHUB_PROXY_ENABLED:-1}

volumes:
  data_db:
  data_configdb:
  data_notebooks:
  certificates:
